version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: lab1
    environment:
      POSTGRES_USER: snowflake
      POSTGRES_PASSWORD: snowflake
      POSTGRES_DB: snowflake
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/data:ro
      - ./ddl/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
      - ./dml/load_data.sql:/docker-entrypoint-initdb.d/2_load_data.sql:ro    