version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    container_name: da-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snowflake
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data